apiVersion: apps/v1
kind: Deployment
metadata:
  name: attendance-app
  labels:
    app: attendance-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: attendance-app
  template:
    metadata:
      labels:
        app: attendance-app
    spec:
      containers:
      - name: attendance-app
        image: nginx:latest
        ports:
        - containerPort: 80